name: ligo
dependencies:
  - python=3.9        # confirmed by running on binder notebook, skeleton from ChatGPT-5
  - scipy=1.13
  - matplotlib=3.9
  - h5py=3.12
  - ipykernel=6.29

  #Confirmed runs!
